backend:
  name: git-gateway
  repo: code-istvan/bw
  branch: master
  site_domain: https://lucid-easley-756a67.netlify.app

media_folder: "static/blogpostimages"
public_folder: "/blogpostimages"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    extension: ".md"
    format: frontmatter
    fields: # The fields for each document, usually in front matter # - { label: Slug, name: slug, required: true, widget: string }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          value_field: "name",
          display_fields: ["name"],
          search_fields: ["name", "email"],
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "authors"
    label: "Authors"
    folder: "static/blogpostimages/_authors"
    media_folder: ""
    public_folder: ""
    format: "json"
    create: true
    slug: "{{name}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Email, name: email, widget: string }
      - { label: Shortbio, name: shortbio, widget: text }
      - { label: Image, name: authorimage, widget: image }

  - name: "schedule"
    label: "Schedule"
    folder: "static/schedule"
    media_folder: ""
    public_folder: ""
    format: "json"
    create: true
    identifier_field: "date"
    slug: "{{date}}"
    fields:
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Date",
          name: "date",
          widget: "datetime",
          date_format: "YYYY.MM.DD",
          format: "LL",
          picker_utc: false,
        }

      - {
          label: Class1,
          name: class1,
          widget: relation,
          collection: "classes",
          value_field: "class",
          display_fields: ["class"],
          search_fields: ["class", "signup"],
        }
      - {
          label: Time,
          name: time1,
          widget: relation,
          collection: "customdate",
          value_field: "customdate",
          display_fields: ["customdate"],
          search_fields: ["customdate"],
        }
      - {
          label: Teacher,
          name: teacher1,
          widget: relation,
          collection: "teachers",
          value_field: "name",
          display_fields: ["name"],
          search_fields: ["name", "link"],
        }

      - {
          label: Class2,
          name: class2,
          widget: relation,
          collection: "classes",
          value_field: "class",
          display_fields: ["class"],
          search_fields: ["class", "signup"],
          required: false,
        }
      - { label: Time, name: time2, widget: string, required: false }
      - {
          label: Teacher,
          name: teacher2,
          widget: relation,
          collection: "teachers",
          value_field: "name",
          display_fields: ["name"],
          search_fields: ["name", "link"],
          required: false,
        }
      - {
          label: Class3,
          name: class3,
          widget: relation,
          collection: "classes",
          value_field: "class",
          display_fields: ["class"],
          search_fields: ["class", "signup"],
          required: false,
        }
      - { label: Time, name: time3, widget: string, required: false }
      - {
          label: Teacher,
          name: teacher3,
          widget: relation,
          collection: "teachers",
          value_field: "name",
          display_fields: ["name"],
          search_fields: ["name", "link"],
          required: false,
        }
      - {
          label: Class4,
          name: class4,
          widget: relation,
          collection: "classes",
          value_field: "class",
          display_fields: ["class"],
          search_fields: ["class", "signup"],
          required: false,
        }
      - { label: Time, name: time4, widget: string, required: false }
      - {
          label: Teacher,
          name: teacher4,
          widget: relation,
          collection: "teachers",
          value_field: "name",
          display_fields: ["name"],
          search_fields: ["name", "link"],
          required: false,
        }

  - name: "events"
    label: "Events"
    folder: "static/events"
    media_folder: ""
    public_folder: ""
    format: "json"
    create: true
    slug: "{{eventid}}"
    fields:
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Featured",
          name: "featured",
          widget: "boolean",
          default: true,
        }
      - { label: Eventid, name: eventid, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Shortdescription, name: Shortdescription, widget: text }
      - { label: Eventlink, name: eventlink, widget: string }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: Day, name: day, widget: string }
      - {
          label: Teacher,
          name: teacher,
          widget: relation,
          collection: "teachers",
          value_field: "name",
          display_fields: ["name"],
          search_fields: ["name", "link"],
        }

  - name: "teachers"
    label: "Teachers"
    folder: "static/teachers"
    media_folder: ""
    public_folder: ""
    format: "json"
    create: true
    slug: "{{name}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Link, name: link, widget: string, required: false }
      - { label: Image, name: teacherimage, widget: image, required: false }

  - name: "classes"
    label: "Classes"
    folder: "static/classes"
    media_folder: ""
    public_folder: ""
    format: "json"
    create: true
    slug: "{{classid}}"
    fields:
      - { label: Classid, name: classid, widget: string }
      - { label: Class, name: class, widget: string }
      - {
          label: Shortdescription,
          name: shortdescription,
          widget: text,
          required: false,
        }
      - { label: Signup, name: signup, widget: string, required: false }

  - name: "customdate"
    label: "Customdate"
    folder: "static/customdate"
    media_folder: ""
    public_folder: ""
    format: "json"
    create: true
    slug: "{{customdate}}"
    fields:
      - { label: Customdate, name: customdate, widget: string }
